# Generated by Django 2.1.7 on 2019-03-18 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(blank=True, max_length=254, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=255)),
                ('phoneno', models.BigIntegerField(default=0)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(blank=True, max_length=255, upload_to='profile_pics')),
                ('pincode', models.IntegerField(default=0)),
                ('is_staff', models.BooleanField(default=False, help_text='Is the user allowed to have access to the admin', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Is the user account currently active', verbose_name='active')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='brand',
            fields=[
                ('brandid', models.AutoField(primary_key=True, serialize=False)),
                ('brandname', models.CharField(default='empty', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('cartid', models.AutoField(primary_key=True, serialize=False)),
                ('qty', models.IntegerField(default='empty')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('categoryid', models.AutoField(primary_key=True, serialize=False)),
                ('catname', models.CharField(default='empty', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('commentid', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=70)),
                ('phone', models.CharField(default='', max_length=70)),
                ('desc', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('orderdate', models.DateField(default=django.utils.timezone.now)),
                ('items_json', models.CharField(default='', max_length=5000)),
                ('name', models.CharField(default='', max_length=90)),
                ('email', models.CharField(max_length=111)),
                ('address', models.CharField(default='', max_length=111)),
                ('city', models.CharField(default='', max_length=111)),
                ('state', models.CharField(default='', max_length=111)),
                ('zip_code', models.CharField(default='', max_length=111)),
                ('phone', models.CharField(default='', max_length=111)),
                ('total', models.IntegerField(default='')),
                ('payment_mode', models.CharField(default='Cash On Delivery', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='orderupdate',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(default='')),
                ('update_desc', models.CharField(max_length=5000)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('productid', models.AutoField(primary_key=True, serialize=False)),
                ('brandname', models.CharField(default='empty', max_length=30)),
                ('producttitle', models.CharField(default='empty', max_length=255)),
                ('productimage1', models.ImageField(default='empty', max_length=255, upload_to='shop/images')),
                ('productimage2', models.ImageField(default='empty', max_length=255, upload_to='shop/images')),
                ('productimage3', models.ImageField(default='empty', max_length=255, upload_to='shop/images')),
                ('productcolor', models.TextField(default='empty', max_length=255)),
                ('productprice', models.IntegerField(default='empty')),
                ('productdesc', models.TextField()),
                ('productstock', models.IntegerField(default='empty')),
                ('catname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bgautosapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('orderdate', models.DateField(default=django.utils.timezone.now)),
                ('Items', models.CharField(default='', max_length=5000)),
                ('Name', models.CharField(default='', max_length=90)),
                ('Email', models.CharField(max_length=111)),
                ('Address', models.CharField(default='', max_length=111)),
                ('City', models.CharField(default='', max_length=111)),
                ('State', models.CharField(default='', max_length=111)),
                ('Zip_code', models.CharField(default='', max_length=111)),
                ('Phone', models.CharField(default='', max_length=111)),
                ('Total', models.IntegerField(default='')),
                ('Payment_mode', models.CharField(default='Cash On Delivery', max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='productid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bgautosapp.product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='productid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bgautosapp.product'),
        ),
    ]
