# Generated by Django 2.1.5 on 2019-03-23 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bgautosapp', '0002_remove_customer_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='productstock',
        ),
    ]
